//
//  Constants.h
//  DigitalTextAnalysis
//
//  Created by Sawyer Bowman on 4/21/15.
//  Copyright (c) 2015 Sawyer Bowman. All rights reserved.
//

#ifndef __DigitalTextAnalysis__Constants__
#define __DigitalTextAnalysis__Constants__

#include <stdio.h>
#include <iostream>
#include <fstream>
#include <sstream>
#include <vector>

#include "Chapter.h"

using namespace std;

//Taken from Voyant-Tools
const vector<string> stopwords = {
    "al",
    "alguna",
    "algunas",
    "alguno",
    "algunos",
    "algún",
    "ambos",
    "ampleamos",
    "ante",
    "antes",
    "aquel",
    "aquellas",
    "aquellos",
    "aqui",
    "arriba",
    "atras",
    "bajo",
    "bastante",
    "bien",
    "cada",
    "cierta",
    "ciertas",
    "ciertos",
    "como",
    "con",
    "conseguimos",
    "conseguir",
    "consigo",
    "consigue",
    "consiguen",
    "consigues",
    "cual",
    "cuando",
    "de",
    "del",
    "dentro",
    "donde",
    "dos",
    "el",
    "ellas",
    "ellos",
    "empleais",
    "emplean",
    "emplear",
    "empleas",
    "empleo",
    "en",
    "encima",
    "entonces",
    "entre",
    "era",
    "eramos",
    "eran",
    "eras",
    "eres",
    "es",
    "esta",
    "estaba",
    "estado",
    "estais",
    "estamos",
    "estan",
    "estoy",
    "fin",
    "fue",
    "fueron",
    "fui",
    "fuimos",
    "gueno",
    "ha",
    "hace",
    "haceis",
    "hacemos",
    "hacen",
    "hacer",
    "haces",
    "hago",
    "incluso",
    "intenta",
    "intentais",
    "intentamos",
    "intentan",
    "intentar",
    "intentas",
    "intento",
    "ir",
    "la",
    "largo",
    "las",
    "lo",
    "los",
    "mientras",
    "mio",
    "modo",
    "muchos",
    "muy",
    "nos",
    "nosotros",
    "o",
    "otro",
    "para",
    "pero",
    "podeis",
    "podemos",
    "poder",
    "podria",
    "podriais",
    "podriamos",
    "podrian",
    "podrias",
    "por",
    "por qué",
    "porque",
    "primero desde",
    "puede",
    "pueden",
    "puedo",
    "que",
    "quien",
    "sabe",
    "sabeis",
    "sabemos",
    "saben",
    "saber",
    "sabes",
    "se",
    "ser",
    "si",
    "siendo",
    "sin",
    "sobre",
    "sois",
    "solamente",
    "solo",
    "somos",
    "soy",
    "su",
    "sus",
    "también",
    "teneis",
    "tenemos",
    "tener",
    "tengo",
    "tiempo",
    "tiene",
    "tienen",
    "todo",
    "trabaja",
    "trabajais",
    "trabajamos",
    "trabajan",
    "trabajar",
    "trabajas",
    "trabajo",
    "tras",
    "tuyo",
    "ultimo",
    "un",
    "una",
    "unas",
    "uno",
    "unos",
    "usa",
    "usais",
    "usamos",
    "usan",
    "usar",
    "usas",
    "uso",
    "va",
    "vais",
    "valor",
    "vamos",
    "van",
    "vaya",
    "verdad",
    "verdadera cierto",
    "verdadero",
    "vosotras",
    "vosotros",
    "voy",
    "y",
    "yo"
};

#endif /* defined(__DigitalTextAnalysis__Constants__) */
